JOB_TITLES = (
    "Economics",
    "Sociology",
    "Physics",
    "Chemistry",
    "Biology",
    "Geology",
    "Political Science",
    "Civil Engineering",
    "Mechanical Engineering",
    "Chemical Engineering",
    "Food Engineering",
    "Construction Technology Management",
    "Computer Engineering",
    "Biomedical Engineering",
    "Computer Science",
    "Information Technology",
    "Software Engineering",
    "Cybersecurity",
    "Data Science",
    "Artificial Intelligence",
    "Accounting",
    "Marketing",
    "Business Management",
    "Graphics Designer",
    "Medicine",
)

DEFAULT_SOURCE_CHANNELS = (
    "hahujobsforfreshgraduates",
    "freelance_ethio",
    "harmeejobs",
    "hahujobs",
    "ethiojobsofficial",
    "effoyjobs",
    "geezjobs_ethiopia",
    "jobs_in_ethio",
)
